services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  api:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      - API_BASE=${API_BASE}
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:8501"
    depends_on:
      - api

volumes:
  postgres_data:

